import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../../components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <div className="grid grid-cols-1 md:grid-cols-[400px_1fr] h-screen">
          {/* Sidebar with Image */}
          <aside className="bg-gray-100 flex justify-center items-center sm:h-full h-48">
            <img
              src="https://s3-alpha-sig.figma.com/img/3f40/ce0c/a2c88fc50cae75b890a2e31799611d61?Expires=1739145600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=nJQyx6~LoTb7JNyzVawd5G2o1BJ0gOqyNSnL2Bm9H0HfUVHuY5MLA0YiopbqcR0BxImnioxuK0v0mrMsSUg4nh5wRK~0TI8inQzf9~pQGvJhGudfouX2UPb9-eG97x2UeLuTl7HoolcvFUasDJA~FzzVOrNAHQYCpkJNZBeZMljgErjAQVauGLLo16M-wybg-g~ZxhTiIzvOcj2hZMaa9CCdYpkgz2ce7lCVLAw4jdjRwXUTD699e~IQ8AstP4~ITlqBzGQ8OqXsr8pu2Qm6nPRpIFehcT5C~fQwYNDQ6cB0loIEiHUTSbdkAvHIsxTE5zgqp~FV7Z~cQ~HnEVbO5g__"
              alt="Sidebar Image"
              className="w-full h-full object-cover"
            />
          </aside>

          {/* Navbar and Content Area */}
          <div className="flex flex-col h-full">
            {/* Navbar */}
            <Navbar />

            {/* Main Content Area */}
            <main className="flex-grow overflow-auto p-2 md:ml-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
